from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ThemeAssetSpec:
    key: str
    relative_path: str
    width: int
    height: int
    category: str
    purpose: str
    required: bool = False


THEME_ASSET_SPECS: tuple[ThemeAssetSpec, ...] = (
    ThemeAssetSpec("background.window", "backgrounds/window.png", 1600, 900, "Background", "Full launcher background, including unused outer areas."),
    ThemeAssetSpec("background.center", "backgrounds/center.png", 980, 900, "Background", "Center column behind pages and the launch control."),
    ThemeAssetSpec("background.sidebar", "backgrounds/sidebar.png", 220, 900, "Background", "Left navigation sidebar."),
    ThemeAssetSpec("background.right_panel", "backgrounds/right_panel.png", 400, 900, "Background", "Right session/status panel."),
    ThemeAssetSpec("background.launch_control", "backgrounds/launch_control.png", 980, 120, "Background", "Permanent launch bar at the bottom of the center column."),
    ThemeAssetSpec("background.page.home", "backgrounds/pages/home.png", 980, 780, "Page background", "Home page viewport."),
    ThemeAssetSpec("background.page.accounts", "backgrounds/pages/accounts.png", 980, 780, "Page background", "Accounts page viewport."),
    ThemeAssetSpec("background.page.instances", "backgrounds/pages/instances.png", 980, 780, "Page background", "Instances page viewport."),
    ThemeAssetSpec("background.page.instance_settings", "backgrounds/pages/instance_settings.png", 980, 780, "Page background", "Instance Settings page viewport."),
    ThemeAssetSpec("background.page.launcher_settings", "backgrounds/pages/launcher_settings.png", 980, 780, "Page background", "Launcher Settings page viewport."),
    ThemeAssetSpec("background.page.logs", "backgrounds/pages/logs.png", 980, 780, "Page background", "Logs page viewport."),
    ThemeAssetSpec("background.page.about", "backgrounds/pages/about.png", 980, 780, "Page background", "About page viewport."),
    ThemeAssetSpec("background.dialog.mod_manager", "backgrounds/dialogs/mod_manager.png", 1050, 680, "Dialog background", "Fabric Mod Manager dialog."),
    ThemeAssetSpec("background.dialog.modrinth", "backgrounds/dialogs/modrinth.png", 1120, 720, "Dialog background", "Modrinth mod and modpack browser."),
    ThemeAssetSpec("background.dialog.update", "backgrounds/dialogs/update.png", 680, 520, "Dialog background", "Update confirmation dialog."),
    ThemeAssetSpec("background.dialog.message", "backgrounds/dialogs/message.png", 520, 260, "Dialog background", "QMessageBox confirmation, warning and error dialogs."),
    ThemeAssetSpec("surface.microsoft_card", "surfaces/cards/microsoft.png", 480, 280, "Surface", "Account creation card with Microsoft approval status."),
    ThemeAssetSpec("surface.java_card", "surfaces/cards/java.png", 480, 260, "Surface", "Java installation scanner and diagnostics card."),
    ThemeAssetSpec("surface.lifecycle_card", "surfaces/cards/lifecycle.png", 480, 440, "Surface", "Backup and Modrinth pack lifecycle card."),
    ThemeAssetSpec("surface.security_card", "surfaces/cards/security.png", 480, 260, "Surface", "Microsoft account protection and database integrity card."),
    ThemeAssetSpec("surface.card", "surfaces/card.png", 480, 240, "Surface", "Normal card. Designed as a stretchable nine-slice surface."),
    ThemeAssetSpec("surface.hero_card", "surfaces/hero_card.png", 920, 230, "Surface", "Large Home hero card."),
    ThemeAssetSpec("surface.inset", "surfaces/inset.png", 440, 180, "Surface", "Inset panels and secondary surfaces."),
    ThemeAssetSpec("surface.table", "surfaces/table.png", 920, 500, "Surface", "Table body background."),
    ThemeAssetSpec("surface.table_header", "surfaces/table_header.png", 920, 40, "Surface", "Table header row."),
    ThemeAssetSpec("surface.log", "surfaces/log_output.png", 920, 560, "Surface", "Launcher activity log output."),
    ThemeAssetSpec("surface.details", "surfaces/details.png", 920, 260, "Surface", "Read-only mod details and update release notes."),
    ThemeAssetSpec("surface.group_box", "surfaces/group_box.png", 480, 180, "Surface", "Group box background for current or future grouped controls."),
    ThemeAssetSpec("surface.tab_pane", "surfaces/tabs/pane.png", 920, 500, "Tab", "Tab content pane."),
    ThemeAssetSpec("surface.tab", "surfaces/tabs/default.png", 180, 42, "Tab", "Normal tab button."),
    ThemeAssetSpec("surface.tab_hover", "surfaces/tabs/hover.png", 180, 42, "Tab", "Hovered tab button."),
    ThemeAssetSpec("surface.tab_selected", "surfaces/tabs/selected.png", 180, 42, "Tab", "Selected tab button."),
    ThemeAssetSpec("surface.table_selected", "surfaces/table_selected.png", 920, 40, "Surface", "Selected table row or cell."),
    ThemeAssetSpec("surface.tooltip", "surfaces/tooltip.png", 360, 120, "Surface", "Launcher tooltip background."),
    ThemeAssetSpec("button.default", "controls/buttons/default.png", 240, 48, "Button", "Normal push button."),
    ThemeAssetSpec("button.hover", "controls/buttons/hover.png", 240, 48, "Button", "Hovered push button."),
    ThemeAssetSpec("button.pressed", "controls/buttons/pressed.png", 240, 48, "Button", "Pressed push button."),
    ThemeAssetSpec("button.disabled", "controls/buttons/disabled.png", 240, 48, "Button", "Disabled push button."),
    ThemeAssetSpec("button.primary", "controls/buttons/primary.png", 260, 72, "Button", "Primary action and Launch button."),
    ThemeAssetSpec("button.primary_hover", "controls/buttons/primary_hover.png", 260, 72, "Button", "Hovered primary action."),
    ThemeAssetSpec("button.primary_pressed", "controls/buttons/primary_pressed.png", 260, 72, "Button", "Pressed primary action."),
    ThemeAssetSpec("button.launch", "controls/buttons/launch/default.png", 461, 133, "Launch button", "Dedicated Launch button artwork; may contain baked pixel-art lettering."),
    ThemeAssetSpec("button.launch_hover", "controls/buttons/launch/hover.png", 461, 133, "Launch button", "Hovered Launch button artwork."),
    ThemeAssetSpec("button.launch_pressed", "controls/buttons/launch/pressed.png", 461, 133, "Launch button", "Pressed Launch button artwork."),
    ThemeAssetSpec("button.launch_disabled", "controls/buttons/launch/disabled.png", 461, 133, "Launch button", "Disabled Launch button artwork."),
    ThemeAssetSpec("button.danger", "controls/buttons/danger.png", 240, 48, "Button", "Destructive action."),
    ThemeAssetSpec("button.danger_hover", "controls/buttons/danger_hover.png", 240, 48, "Button", "Hovered destructive action."),
    ThemeAssetSpec("button.nav", "controls/navigation/default.png", 192, 46, "Navigation", "Normal sidebar navigation button."),
    ThemeAssetSpec("button.nav_hover", "controls/navigation/hover.png", 192, 46, "Navigation", "Hovered sidebar navigation button."),
    ThemeAssetSpec("button.nav_selected", "controls/navigation/selected.png", 192, 46, "Navigation", "Selected sidebar navigation button."),
    ThemeAssetSpec("input.default", "controls/input/default.png", 420, 42, "Input", "Line edit, combo box and spin box background."),
    ThemeAssetSpec("input.focus", "controls/input/focus.png", 420, 42, "Input", "Focused single-line input background."),
    ThemeAssetSpec("input.text_area", "controls/input/text_area.png", 640, 140, "Input", "Multiline JVM and game argument editor."),
    ThemeAssetSpec("input.text_area_focus", "controls/input/text_area_focus.png", 640, 140, "Input", "Focused multiline argument editor."),
    ThemeAssetSpec("combo.popup", "controls/combo/popup.png", 420, 320, "Control", "Combo box drop-down list surface."),
    ThemeAssetSpec("checkbox.unchecked", "controls/checkbox/unchecked.png", 24, 24, "Control", "Unchecked checkbox indicator."),
    ThemeAssetSpec("checkbox.checked", "controls/checkbox/checked.png", 24, 24, "Control", "Checked checkbox indicator."),
    ThemeAssetSpec("checkbox.disabled", "controls/checkbox/disabled.png", 24, 24, "Control", "Disabled checkbox indicator."),
    ThemeAssetSpec("combo.arrow", "controls/combo/arrow.png", 20, 20, "Control", "Combo box drop-down arrow."),
    ThemeAssetSpec("progress.track", "controls/progress/track.png", 640, 24, "Progress", "Progress bar track."),
    ThemeAssetSpec("progress.chunk", "controls/progress/chunk.png", 640, 24, "Progress", "Progress bar filled chunk."),
    ThemeAssetSpec("scrollbar.track", "controls/scrollbar/track.png", 16, 256, "Scrollbar", "Vertical scrollbar track."),
    ThemeAssetSpec("scrollbar.handle", "controls/scrollbar/handle.png", 16, 64, "Scrollbar", "Vertical scrollbar handle."),
    ThemeAssetSpec("scrollbar.horizontal_track", "controls/scrollbar/horizontal_track.png", 256, 16, "Scrollbar", "Horizontal scrollbar track."),
    ThemeAssetSpec("scrollbar.horizontal_handle", "controls/scrollbar/horizontal_handle.png", 64, 16, "Scrollbar", "Horizontal scrollbar handle."),
    ThemeAssetSpec("badge.status", "surfaces/badges/status.png", 180, 40, "Badge", "Ready/success status badge."),
    ThemeAssetSpec("badge.warning", "surfaces/badges/warning.png", 180, 40, "Badge", "Warning status badge."),
    ThemeAssetSpec("badge.locked", "surfaces/badges/locked.png", 260, 48, "Badge", "Feature locked or approval-pending status badge."),
    ThemeAssetSpec("badge.error", "surfaces/badges/error.png", 180, 40, "Badge", "Error/failed status badge."),
    ThemeAssetSpec("logo.main", "logos/main.png", 640, 240, "Logo", "Large Home page launcher logo."),
    ThemeAssetSpec("logo.sidebar", "logos/sidebar.png", 192, 72, "Logo", "Optional sidebar brand logo."),
    ThemeAssetSpec("icon.app", "icons/app.png", 256, 256, "Application", "Window and executable icon source."),
    ThemeAssetSpec("icon.nav.home", "icons/navigation/home.png", 32, 32, "Navigation icon", "Home navigation icon."),
    ThemeAssetSpec("icon.nav.accounts", "icons/navigation/accounts.png", 32, 32, "Navigation icon", "Accounts navigation icon."),
    ThemeAssetSpec("icon.nav.instances", "icons/navigation/instances.png", 32, 32, "Navigation icon", "Instances navigation icon."),
    ThemeAssetSpec("icon.nav.instance_settings", "icons/navigation/instance_settings.png", 32, 32, "Navigation icon", "Instance Settings navigation icon."),
    ThemeAssetSpec("icon.nav.launcher_settings", "icons/navigation/launcher_settings.png", 32, 32, "Navigation icon", "Launcher Settings navigation icon."),
    ThemeAssetSpec("icon.nav.logs", "icons/navigation/logs.png", 32, 32, "Navigation icon", "Logs navigation icon."),
    ThemeAssetSpec("icon.nav.about", "icons/navigation/about.png", 32, 32, "Navigation icon", "About navigation icon."),
    ThemeAssetSpec("icon.action.launch", "icons/actions/launch.png", 40, 40, "Action icon", "Launch button."),
    ThemeAssetSpec("icon.action.refresh", "icons/actions/refresh.png", 24, 24, "Action icon", "Refresh/reload actions."),
    ThemeAssetSpec("icon.action.add", "icons/actions/add.png", 24, 24, "Action icon", "Create/add actions."),
    ThemeAssetSpec("icon.action.remove", "icons/actions/remove.png", 24, 24, "Action icon", "Remove/delete actions."),
    ThemeAssetSpec("icon.action.edit", "icons/actions/edit.png", 24, 24, "Action icon", "Rename/edit actions."),
    ThemeAssetSpec("icon.action.clone", "icons/actions/clone.png", 24, 24, "Action icon", "Clone/copy instance action."),
    ThemeAssetSpec("icon.action.import", "icons/actions/import.png", 24, 24, "Action icon", "Import package action."),
    ThemeAssetSpec("icon.action.export", "icons/actions/export.png", 24, 24, "Action icon", "Export package/diagnostics action."),
    ThemeAssetSpec("icon.action.folder", "icons/actions/folder.png", 24, 24, "Action icon", "Open or browse folder/file action."),
    ThemeAssetSpec("icon.action.save", "icons/actions/save.png", 24, 24, "Action icon", "Save settings action."),
    ThemeAssetSpec("icon.action.reset", "icons/actions/reset.png", 24, 24, "Action icon", "Reset settings action."),
    ThemeAssetSpec("icon.action.search", "icons/actions/search.png", 24, 24, "Action icon", "Search action."),
    ThemeAssetSpec("icon.action.previous", "icons/actions/previous.png", 24, 24, "Action icon", "Previous page action."),
    ThemeAssetSpec("icon.action.next", "icons/actions/next.png", 24, 24, "Action icon", "Next page action."),
    ThemeAssetSpec("icon.action.download", "icons/actions/download.png", 24, 24, "Action icon", "Install/download action."),
    ThemeAssetSpec("icon.action.update", "icons/actions/update.png", 24, 24, "Action icon", "Check/apply update action."),
    ThemeAssetSpec("icon.action.modrinth", "icons/actions/modrinth.png", 24, 24, "Action icon", "Browse Modrinth action."),
    ThemeAssetSpec("icon.action.mods", "icons/actions/mods.png", 24, 24, "Action icon", "Manage mods action."),
    ThemeAssetSpec("icon.action.enable", "icons/actions/enable.png", 24, 24, "Action icon", "Enable mod action."),
    ThemeAssetSpec("icon.action.disable", "icons/actions/disable.png", 24, 24, "Action icon", "Disable mod action."),
    ThemeAssetSpec("icon.action.microsoft", "icons/actions/microsoft.png", 24, 24, "Action icon", "Add Microsoft account action."),
    ThemeAssetSpec("icon.action.java", "icons/actions/java.png", 24, 24, "Action icon", "Scan or manage Java installations."),
    ThemeAssetSpec("icon.action.backup", "icons/actions/backup.png", 24, 24, "Action icon", "Create an instance or world backup."),
    ThemeAssetSpec("icon.action.restore", "icons/actions/restore.png", 24, 24, "Action icon", "Restore an MCW backup."),
    ThemeAssetSpec("icon.action.shield", "icons/actions/shield.png", 24, 24, "Action icon", "Verify account protection and database integrity."),
    ThemeAssetSpec("icon.action.reprotect", "icons/actions/reprotect.png", 24, 24, "Action icon", "Re-protect Microsoft account credentials."),
    ThemeAssetSpec("icon.action.account", "icons/actions/account.png", 24, 24, "Action icon", "Account action."),
    ThemeAssetSpec("icon.action.instance", "icons/actions/instance.png", 24, 24, "Action icon", "Instance action."),
    ThemeAssetSpec("icon.action.settings", "icons/actions/settings.png", 24, 24, "Action icon", "Settings action."),
    ThemeAssetSpec("icon.action.copy", "icons/actions/copy.png", 24, 24, "Action icon", "Copy text action."),
    ThemeAssetSpec("icon.action.clear", "icons/actions/clear.png", 24, 24, "Action icon", "Clear output action."),
    ThemeAssetSpec("icon.action.repair", "icons/actions/repair.png", 24, 24, "Action icon", "Repair Fabric/instance action."),
    ThemeAssetSpec("icon.action.language", "icons/actions/language.png", 24, 24, "Action icon", "Reload language packs action."),
    ThemeAssetSpec("icon.action.theme", "icons/actions/theme.png", 24, 24, "Action icon", "Reload/apply theme action."),
    ThemeAssetSpec("icon.action.release", "icons/actions/release.png", 24, 24, "Action icon", "Open GitHub release page."),
    ThemeAssetSpec("icon.state.ready", "icons/states/ready.png", 32, 32, "State icon", "Ready state."),
    ThemeAssetSpec("icon.state.busy", "icons/states/busy.png", 32, 32, "State icon", "Busy/downloading state."),
    ThemeAssetSpec("icon.state.success", "icons/states/success.png", 32, 32, "State icon", "Success/running state."),
    ThemeAssetSpec("icon.state.warning", "icons/states/warning.png", 32, 32, "State icon", "Warning state."),
    ThemeAssetSpec("icon.state.error", "icons/states/error.png", 32, 32, "State icon", "Failure state."),
)

THEME_ASSET_BY_KEY = {spec.key: spec for spec in THEME_ASSET_SPECS}
