from enum import Enum


class JavaSource(Enum):
    PATH = "PATH"
    JAVA_HOME = "JAVA_HOME"
    PROGRAM_FILES = "PROGRAM_FILES"
    REGISTRY = "REGISTRY"
    MINECRAFT_RUNTIME = "MINECRAFT_RUNTIME"
    CUSTOM = "CUSTOM"